// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh6DN4LRVG9Gairn5QOiIcoqPNnaK007U',
    appId: '1:698046899238:web:af64b3ad26094dafbcb2e7',
    messagingSenderId: '698046899238',
    projectId: 'isenecafirebasecarlos',
    authDomain: 'isenecafirebasecarlos.firebaseapp.com',
    storageBucket: 'isenecafirebasecarlos.appspot.com',
    measurementId: 'G-VFGXGGRCPL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaeiJZTcCBPpySMdqv3L3uNz0DBJ_U36c',
    appId: '1:698046899238:android:a97cbbe1f9bf4f58bcb2e7',
    messagingSenderId: '698046899238',
    projectId: 'isenecafirebasecarlos',
    storageBucket: 'isenecafirebasecarlos.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqtzR0L8CC0rA15ZbFbCmftyt1DcXcFaE',
    appId: '1:698046899238:ios:f5ab2424ef05bfb2bcb2e7',
    messagingSenderId: '698046899238',
    projectId: 'isenecafirebasecarlos',
    storageBucket: 'isenecafirebasecarlos.appspot.com',
    androidClientId: '698046899238-bl1s7va0kb5l5e8mai2ln8vntfkjd6h0.apps.googleusercontent.com',
    iosClientId: '698046899238-kf020c67g6hll7t9geem2d317l4fm0j6.apps.googleusercontent.com',
    iosBundleId: 'com.example.iseneca',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqtzR0L8CC0rA15ZbFbCmftyt1DcXcFaE',
    appId: '1:698046899238:ios:37175b98426a5fe5bcb2e7',
    messagingSenderId: '698046899238',
    projectId: 'isenecafirebasecarlos',
    storageBucket: 'isenecafirebasecarlos.appspot.com',
    androidClientId: '698046899238-bl1s7va0kb5l5e8mai2ln8vntfkjd6h0.apps.googleusercontent.com',
    iosClientId: '698046899238-7olfps2sfrglbrm1m6j9kfmtc9m8r32n.apps.googleusercontent.com',
    iosBundleId: 'com.example.iseneca.RunnerTests',
  );
}
